[package]
name = "eight"
version = "0.1.0"
edition = "2024"
default-run = "8"

[lib]
name = "eight"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "8"
path = "src/main.rs"
test = false

[dependencies]
assembler = "0.10.1"
dtor = "1.0.6"
libc = "0.2.189"
xxx = { git = "https://github.com/bleedsa/xxx" }
